### get spesific ticket success test

GET http://localhost/smart-asia-farm/public/api/tiket/1636906766100
Content-Type: application/json
Accept: application/json

###

### get spesific ticket not found test

GET http://localhost/smart-asia-farm/public/api/tiket/abc
Content-Type: application/json
Accept: application/json

###
