### list keranjang

GET http://localhost/smart-asia-farm/public/api/keranjang/
Content-Type: application/json
Accept: application/json

###

### create keranjang success test

POST http://localhost/smart-asia-farm/public/api/keranjang/create
Content-Type: application/json
Accept: application/json

{
  "id_user" : "1",
  "id_wahana" : "1"
}

###

### create keranjang invalid test

POST http://localhost/smart-asia-farm/public/api/keranjang/create
Content-Type: application/json
Accept: application/json

{
  "id_user" : "",
  "id_wahana" : ""
}

###

### inCart true test

POST http://localhost/smart-asia-farm/public/api/keranjang/inCart
Content-Type: application/json
Accept: application/json

{
  "id_user" : "1",
  "id_wahana" : "1"
}

###

### inCart false test

POST http://localhost/smart-asia-farm/public/api/keranjang/inCart
Content-Type: application/json
Accept: application/json

{
  "id_user" : "abc",
  "id_wahana" : "def"
}

###

### inCart  invalid test

POST http://localhost/smart-asia-farm/public/api/keranjang/inCart
Content-Type: application/json
Accept: application/json

{
  "id_user" : "",
  "id_wahana" : ""
}

###

### checkout process success test

POST http://localhost/smart-asia-farm/public/api/keranjang/checkout
Content-Type: application/json
Accept: application/json

{
  "order_id" : "1636355200234",
  "user_id" : "1",
  "book_date" : "2021-11-15",
  "book_time" : "08:00",
  "book_type" : "A",
  "pdf_url" : "https://app.sandbox.midtrans.com/snap/v1/transactions/952c2ab8-2921-422d-93ad-ac4138e67c72/pdf"
}

###

### checkout process invalid data test

POST http://localhost/smart-asia-farm/public/api/keranjang/checkout
Content-Type: application/json
Accept: application/json

{
  "order_id" : "",
  "user_id" : "",
  "book_date" : "",
  "book_time" : "",
  "book_type" : "F",
  "pdf_url" : ""
}

###

### checkout process order not found test

POST http://localhost/smart-asia-farm/public/api/keranjang/checkout
Content-Type: application/json
Accept: application/json

{
  "order_id" : "abc.xyz",
  "user_id" : "1",
  "book_date" : "2021-09-28",
  "book_time" : "08:00",
  "book_type" : "C",
  "pdf_url" : ""
}

###
