### get user charts

GET http://localhost/smart-asia-farm/public/api/user/1/keranjang
Accept: application/json

###

### get user profile success test

GET http://localhost/smart-asia-farm/public/api/user/14
Accept: application/json

###

### get user profile not found test

GET http://localhost/smart-asia-farm/public/api/user/abc
Accept: application/json

###

### update user personal data success test

PUT http://localhost/smart-asia-farm/public/api/user/16
Content-Type: application/json
Accept: application/json

{
   "nama_lengkap" : "Budiman Sudjatmiko",
   "no_hp" : "082174614390",
   "alamat" : "Jl. Rowo Bening",
   "jenis_kelamin" : "laki-laki",
   "tanggal_lahir" : "1998-03-05",
   "tempat_lahir" : "Tembilahan"
}

###

### update user personal data invalid test

PUT http://localhost/smart-asia-farm/public/api/user/16
Content-Type: application/json
Accept: application/json

{
  "nama_lengkap" : "Budiman Sudjatmiko",
  "no_hp" : "082174614390",
  "alamat" : "Jl. Rowo Bening",
  "jenis_kelamin" : "kelamin",
  "tanggal_lahir" : "kambing",
  "tempat_lahir" : ""
}

###

### get user not found user

GET http://localhost/smart-asia-farm/public/api/user/ol/keranjang
Accept: application/json

###

### get authenticated user carts success

GET http://localhost/smart-asia-farm/public/api/user/1/keranjang
Accept: application/json

###

### get authenticated user tickets success

GET http://localhost/smart-asia-farm/public/api/user/17/tiket
Accept: application/json

###

### get authenticated user tickets with filter success

GET http://localhost/smart-asia-farm/public/api/user/1/tiket?status=success
Accept: application/json

###

### get authenticated user tickets, user not found test

GET http://localhost/smart-asia-farm/public/api/user/abc/tiket
Accept: application/json

###

### get authenticated user tickets with invalid enum filter not found

GET http://localhost/smart-asia-farm/public/api/user/1/tiket?status=kambing
Accept: application/json

###
